# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rachel Heo - UI & UX Designer
email: rachelheodesign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Rachel Heo, a freelance UI & UX designer who is based in Vancouver and Seoul.
  I have a passion for creating beautiful, intuitive, and highly crafted designs combining a considered approach with emerging technologies. I have wide ranging skills in designing from web and mobile interfaces to prints and logos.
  My strengths lie in my attention to detail, the ability to refine complex requirements and information into simple and elegant solutions. I am not interested in simply “ticking the boxes” and churning out average designs. I want to make sure that everything I produce is something that I would be excited about if I were the client. I love what I do and I do what I love, and it makes me want to always outdo myself and seek out new challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rachelheodesign.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
